services:
  zookeeper:
    image: otus/zookeeper:v1
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - kafka-net
    ports:
      - "12181:2181"

  kafka:
    image: otus/kafka:v1
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  connect:
    image: otus/connect:v1
    container_name: connect
    hostname: connect
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./connect:/opt/connect
    networks:
      - kafka-net

  postgres:
    image: postgres:16.4
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=kafka
      - POSTGRES_PASSWORD=kafka
      - POSTGRES_DB=connect
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - kafka-net

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - kafka-net
    environment:
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/

  # вспомогательный сервис для доступа к контейнерам по иманам контейнеров
  hoster:
    image: dvdarias/docker-hoster
    container_name: hoster
    networks:
        - kafka-net
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - /etc/hosts:/tmp/hosts

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
