services:
  zookeeper:
    image: otus/zookeeper:v1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "12181:2181"

  kafka:
    image: otus/kafka:v1
    container_name: kafka
    hostname: kafka
    ports:
      - "19092:9092"
    depends_on:
      - zookeeper

