spring.datasource.url=jdbc:postgresql://postgres:5432/connect
spring.datasource.username=postgres
spring.datasource.password=pgpass

spring.kafka.producer.bootstrap-servers=broker:9092

kafka_event.topic=events_topic

