akka {
  windowStep = "10s"
  windowLength = "30s"
  kafka {
    consumer {
      kafka-clients {
        enable.auto.commit = true
        bootstrap.servers = "broker:9092"
        group.id = "group1"
        auto.offset.reset = "earliest"
      }
      topic = "events_topic"
    }
  }
}