akka {
  kafka {
    consumer {
      kafka-clients {
        enable.auto.commit = true
        bootstrap.servers = "kafka:9092"
        group.id = "group1"
        auto.offset.reset = "earliest"
      }
    }
  }
}