kotlin.code.style=official

springVersion=2.7.14
jacksonVersion=2.10.3
postgresVersion=42.7.4

kotlinxCoroutinesVersion=1.7.3
kotlinxSerializationJson=1.5.0
kotlinxCoroutinesSlf4jVersion=1.7.3
kotlinCoroutinesJdk8Version=1.8.1
kotlinxCoroutinesCoreJVMVersion=1.7.1
kotlinReflectVersion=1.7.22

logbackVersion=1.2.13
slf4jVersion=1.7.36
springdocVersion=1.8.0
jedisVersion=3.10.0
flywayVersion=9.22.2
